title: Erebus Scripts Docs
description: Documentation and information about Erebus Scripts
theme: just-the-docs

url: https://erebus-3222.github.io/erebus-3222.github.io

aux_links: # remove if you don't want this link to appear on your pages
  Store Page: https://erebus-scripts.tebex.io/


  # Enable or disable the site search
# Supports true (default) or false
search_enabled: true
